class AppConnectionError(Exception):
    """Вызывается при не возможности подключения к приложению"""
